(ns astgrep.jobject-cpp)

(def jobject-cpp
  '[{:kind "ClassTemplate" :Template 
     {:name "C" :line [4 10] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"
      :Member [{:kind "Field" :name "x" :scope "member" :type {:kind "Unknown-type" :typeSting "Ty"} :line [5 5] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"}
               {:kind "Field" :name "y" :scope "member" :type {:kind "Typedef-type" :typename "jobject" :type {:kind "Pointer-type" :Pointee {:kind "Char-type"}}} :line [6 6] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"}
               {:kind "Method" :name "C::yabai" :type {:kind "Void-type"} :line [7 9] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"
                :Parm [{:kind "Parm" :name "o" :type {:kind "Typedef-type" :typename "jobject" :type {:kind "Pointer-type" :Pointee {:kind "Char-type"}}} :line [7 7] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"}]
                :body [{:kind "Binop" :op "=" :line [8 8] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"
                        :LHS {:kind "Field" :name "y" :scope "member" :type {:kind "Typedef-type" :typename "jobject" :type {:kind "Pointer-type" :Pointee {:kind "Char-type"}}} :line [6 6] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"}
                        :RHS {:kind "DRE" :name "o" :scope "local" :type {:kind "Typedef-type" :typename "jobject" :type {:kind "Pointer-type" :Pointee {:kind "Char-type"}}} :line [8 8] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"}}]}]}}
    {:kind "Funcdef" :name "main" :type {:kind "Int-type"} :line [12 14] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"
     :Parm []
     :body [{:kind "Ret" :line [13 13] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp" :value {:kind "IntegerLiteral" :value "0" :type {:kind "Int-type"} :line [13 13] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"}}]}
    {:kind "Var" :name "obj" :scope "global" :type {:kind "Unknown-type" :typeSting "class C<float>"} :line [17 17] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"
     :init {:kind "Unknown"}}{:kind "Var" :name "obj2" :scope "global" :type {:kind "Unknown-type" :typeSting "class C<double>"} :line [18 18] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"
                              :init {:kind "Unknown"}}{:kind "Var" :name "obj3" :scope "global" :type {:kind "Unknown-type" :typeSting "class C<long long>"} :line [19 19] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"
                                                       :init {:kind "Unknown"}}{:kind "Var" :name "obj4" :scope "global" :type {:kind "Typedef-type" :typename "C_char" :type {:kind "Unknown-type" :typeSting "C<char>"}} :line [21 21] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"
                                                                                :init {:kind "Unknown"}}{:kind "Var" :name "global_jobject" :scope "global" :type {:kind "Typedef-type" :typename "jobject" :type {:kind "Pointer-type" :Pointee {:kind "Char-type"}}} :line [23 23] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"}
    {:kind "ClassTemplate" :Template 
     {:name "CC" :line [26 35] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"
      :Member [{:kind "Field" :name "aaa" :scope "member" :type {:kind "Unknown-type" :typeSting "T"} :line [27 27] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"}
               {:kind "Field" :name "y" :scope "member" :type {:kind "Typedef-type" :typename "jobject" :type {:kind "Pointer-type" :Pointee {:kind "Char-type"}}} :line [28 28] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"}
               {:kind "Method" :name "CC::badfunc" :type {:kind "Void-type"} :line [29 31] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"
                :Parm [{:kind "Parm" :name "x" :type {:kind "Typedef-type" :typename "jobject" :type {:kind "Pointer-type" :Pointee {:kind "Char-type"}}} :line [29 29] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"}]
                :body [{:kind "Binop" :op "=" :line [30 30] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"
                        :LHS {:kind "DRE" :name "global_jobject" :scope "global" :type {:kind "Typedef-type" :typename "jobject" :type {:kind "Pointer-type" :Pointee {:kind "Char-type"}}} :line [30 30] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"}
                        :RHS {:kind "DRE" :name "x" :scope "local" :type {:kind "Typedef-type" :typename "jobject" :type {:kind "Pointer-type" :Pointee {:kind "Char-type"}}} :line [30 30] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"}}]}
               {:kind "Method" :name "CC::badfunc2" :type {:kind "Void-type"} :line [32 34] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"
                :Parm [{:kind "Parm" :name "z" :type {:kind "Typedef-type" :typename "jobject" :type {:kind "Pointer-type" :Pointee {:kind "Char-type"}}} :line [32 32] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"}]
                :body [{:kind "Binop" :op "=" :line [33 33] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"
                        :LHS {:kind "Field" :name "y" :scope "member" :type {:kind "Typedef-type" :typename "jobject" :type {:kind "Pointer-type" :Pointee {:kind "Char-type"}}} :line [28 28] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"}
                        :RHS {:kind "DRE" :name "z" :scope "local" :type {:kind "Typedef-type" :typename "jobject" :type {:kind "Pointer-type" :Pointee {:kind "Char-type"}}} :line [33 33] :Filename  "/home/nakamura/clangws/bcmacro-cast/astprint/llvm34/build_ninja/../../../samplecode/jobject.cpp"}}]}]}}])
